// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHN8db7miLBWjphVuQEOEAHATRGIn_yM',
    appId: '1:396484119541:web:3607380b8f07fd27f3eebc',
    messagingSenderId: '396484119541',
    projectId: 'electronic-commerce-app',
    authDomain: 'electronic-commerce-app.firebaseapp.com',
    storageBucket: 'electronic-commerce-app.appspot.com',
    measurementId: 'G-EEVYTCT4B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGd0QrmsvEsmilo2-bKPbc1nkacEeMZOY',
    appId: '1:396484119541:android:74383000aa9bb46cf3eebc',
    messagingSenderId: '396484119541',
    projectId: 'electronic-commerce-app',
    storageBucket: 'electronic-commerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX1plhBJWkblo1ucpA56LZvTy8KuP3AUs',
    appId: '1:396484119541:ios:92661eb3fdee7aabf3eebc',
    messagingSenderId: '396484119541',
    projectId: 'electronic-commerce-app',
    storageBucket: 'electronic-commerce-app.appspot.com',
    iosBundleId: 'com.example.electronicEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX1plhBJWkblo1ucpA56LZvTy8KuP3AUs',
    appId: '1:396484119541:ios:92661eb3fdee7aabf3eebc',
    messagingSenderId: '396484119541',
    projectId: 'electronic-commerce-app',
    storageBucket: 'electronic-commerce-app.appspot.com',
    iosBundleId: 'com.example.electronicEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATHN8db7miLBWjphVuQEOEAHATRGIn_yM',
    appId: '1:396484119541:web:8793a206e4fd9373f3eebc',
    messagingSenderId: '396484119541',
    projectId: 'electronic-commerce-app',
    authDomain: 'electronic-commerce-app.firebaseapp.com',
    storageBucket: 'electronic-commerce-app.appspot.com',
    measurementId: 'G-9MZYC20H0M',
  );
}
